{
 "title": "HAproxy metric eng",
 "description": "influxdb database template for haproxy english version",
 "tags": [
  "haproxy",
  "influxdb",
  "Pre-release"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "server",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"host\""
   },
   {
    "name": "proxy",
    "label": "service name",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"proxy\""
   },
   {
    "name": "sv",
    "label": "application",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"sv\""
   }
  ]
 },
 "panels": [
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Servers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active_servers\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "req_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Bin",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bin\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Bout",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bout\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Ttime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ttime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "rtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "http_response.1xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.1xx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "http_response.2xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.2xx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "http_response.3xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.3xx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "http_response.4xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.4xx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "http_response.5xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.5xx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "http_response.other",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.other\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  }
 ]
}