{
 "title": "Super Simple Nginx Dashboard",
 "description": "The most simples nginx dashboard possible",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hosts\",\r\n  tag: \"host\",\r\n  predicate: (r) => r[\"_measurement\"] == \"nginx\",\r\n)\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /$host/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Total Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /$host/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"accepts\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /$host/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"requests\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /$host/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /$host/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"handled\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"hosts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /$host/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"accepts\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}